-- 코드를 입력하세요
-- SELECT PRODUCT_ID,PRODUCT_NAME,PRODUCT_CD,CATEGORY,PRICE
SELECT *
FROM FOOD_PRODUCT
-- ORDER BY PRICE DESC
WHERE PRICE=(SELECT MAX (PRICE) FROM FOOD_PRODUCT )
-- LIMIT 1
-- 비추천 코드 : 최고가 식품 인스턴스가 여러 개 일수도 있다.