SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE YEAR(JOINED) = 2021 AND AGE BETWEEN 20 AND 29;
-- WHERE JOINED LIKE '2021%'
-- AND AGE BETWEEN 20 AND 29
-- SELECT COUNT(*) AS USERS
-- FROM USER_INFO
-- WHERE AGE >= 20 AND AGE <= 29 AND YEAR(JOINED) = 2021