-- 코드를 입력하세요
SELECT MCDP_CD AS '진료과코드',
COUNT(APNT_YMD) AS '5월예약건수'
FROM APPOINTMENT
WHERE YEAR(APNT_YMD)='2022' and MONTH(APNT_YMD)='5'
-- WHERE APNT_YMD LIKE '2022-05%'
-- WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
-- GROUP BY 1
GROUP BY MCDP_CD 
ORDER BY 2,1